version: 2

defaults:
  workspace_root: &workspace_root
    ~/cadastredatagouv

  container: &default_container
    working_directory: *workspace_root
    docker:
      - image: circleci/node:8

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_node_modules: &restore_node_modules
    restore_cache:
      name: Restore node_modules cache
      keys:
        - v1-cadastredatagouv-node-{{ checksum "yarn.lock" }}
        - v1-cadastredatagouv-node-

jobs:
  install:
    <<: *default_container
    steps:
      - checkout

      - restore_cache:
          name: Restore yarn cache
          keys:
            - v1-cadastredatagouv-yarn-{{ checksum "yarn.lock" }}
            - v1-cadastredatagouv-yarn-

      - *restore_node_modules

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          name: Save yarn cache
          key: v1-cadastredatagouv-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/

      - save_cache:
          name: Save node_modules cache
          key: v1-cadastredatagouv-node-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

      - run:
          name: Remove node_modules to cleanup workspace
          command: rm -r node_modules/

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./

  build:
    <<: *default_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - run:
          name: Build output bundles
          command: yarn dist

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - dist/

  deploy:
    <<: *default_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - add_ssh_keys:
          fingerprints:
            - 63:c6:b8:d7:85:98:4c:0b:f4:1b:dd:ed:57:dc:d8:95

      - run:
          name: Setup SSH to GitHub
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts

      - run:
          name: Set SSH user email
          command: git config --global user.email "infra@data.gouv.fr"

      - run:
          name: Set SSH user name
          command: git config --global user.name "CircleCI"

      - deploy:
          name: Deploy to gh-pages branch on GitHub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn deploy
            fi

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - install

      - build:
          requires:
            - install

      - deploy:
          requires:
            - build
